import { PrismaClient, ChallengeCategory, ArticleCategory } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main(): Promise<void> {
  console.log('🌱 Starting database seed...');

  // Create admin user
  const adminHash = await bcrypt.hash('Admin@123456', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@carbontrack.io' },
    update: {},
    create: {
      email: 'admin@carbontrack.io',
      name: 'Platform Admin',
      passwordHash: adminHash,
      role: 'ADMIN',
    },
  });
  console.log(`✅ Admin user: ${admin.email}`);

  // Create demo user
  const demoHash = await bcrypt.hash('Demo@123456', 12);
  const demo = await prisma.user.upsert({
    where: { email: 'demo@carbontrack.io' },
    update: {},
    create: {
      email: 'demo@carbontrack.io',
      name: 'Demo User',
      passwordHash: demoHash,
    },
  });
  console.log(`✅ Demo user: ${demo.email}`);

  // Seed challenges
  const challengesData = [
    {
      title: 'Public Transport Week',
      description: 'Use only public transport for 7 consecutive days. Avoid personal vehicles completely.',
      category: ChallengeCategory.TRANSPORT,
      points: 50,
      badge: 'Transit Champion',
      duration: 7,
      tips: ['Plan routes in advance', 'Get a transit card for easy access', 'Track your CO₂ savings'],
    },
    {
      title: 'Meat-Free Week',
      description: 'Go one full week without eating meat. Explore delicious plant-based alternatives.',
      category: ChallengeCategory.FOOD,
      points: 40,
      badge: 'Plant Powered',
      duration: 7,
      tips: ['Try lentil soups and bean stews', 'Explore tofu and tempeh recipes', 'Visit a vegetarian restaurant'],
    },
    {
      title: 'Zero Single-Use Plastic',
      description: 'Eliminate single-use plastics from your daily routine for a full month.',
      category: ChallengeCategory.WASTE,
      points: 60,
      badge: 'Plastic Free Hero',
      duration: 30,
      tips: ['Use a reusable water bottle', 'Bring your own bags', 'Choose products with minimal packaging'],
    },
    {
      title: 'Cycle Commuter',
      description: 'Cycle to work or for errands at least 5 times this week.',
      category: ChallengeCategory.TRANSPORT,
      points: 35,
      badge: 'Pedal Power',
      duration: 7,
      tips: ['Check your bike\'s tyre pressure', 'Plan a safe cycle route', 'Use cycling apps for navigation'],
    },
    {
      title: 'Energy Saver',
      description: 'Reduce your home electricity consumption by 20% this month.',
      category: ChallengeCategory.ENERGY,
      points: 45,
      badge: 'Energy Guardian',
      duration: 30,
      tips: ['Switch to LED bulbs', 'Unplug devices when not in use', 'Use smart power strips'],
    },
    {
      title: 'Plant a Tree',
      description: 'Plant at least one tree in your garden or participate in a community tree-planting event.',
      category: ChallengeCategory.LIFESTYLE,
      points: 70,
      badge: 'Green Warrior',
      duration: 14,
      tips: ['Choose native tree species', 'Water regularly after planting', 'Share your experience on social media'],
    },
    {
      title: 'Recycling Master',
      description: 'Achieve 80%+ recycling rate for all household waste this month.',
      category: ChallengeCategory.WASTE,
      points: 30,
      badge: 'Recycling Star',
      duration: 30,
      tips: ['Learn your local recycling rules', 'Set up separate bins', 'Compost food waste'],
    },
    {
      title: 'Cold Shower Challenge',
      description: 'Take only cold or lukewarm showers for 2 weeks to reduce energy usage.',
      category: ChallengeCategory.ENERGY,
      points: 25,
      badge: 'Cool Conservationist',
      duration: 14,
      tips: ['Start with 30 seconds of cold water', 'Gradually extend the duration', 'Use a shower timer'],
    },
  ];

  for (const challenge of challengesData) {
    await prisma.challenge.upsert({
      where: { id: challenge.title.replace(/ /g, '-').toLowerCase() },
      update: {},
      create: { id: challenge.title.replace(/ /g, '-').toLowerCase(), ...challenge },
    });
  }
  console.log(`✅ ${challengesData.length} challenges seeded`);

  // Seed articles
  const articlesData = [
    {
      title: 'What Is Carbon Footprint and Why Does It Matter?',
      slug: 'what-is-carbon-footprint',
      excerpt: 'Understanding your carbon footprint is the first step towards a more sustainable life.',
      content: `## What Is a Carbon Footprint?

A carbon footprint is the total amount of greenhouse gases—including carbon dioxide and methane—that are generated by our actions. It is typically measured in tonnes of CO₂ equivalent (CO₂e) per year.

## Why It Matters

The global average carbon footprint is around 4 tonnes per person per year. To limit global warming to 1.5°C, the average must drop to under 2 tonnes by 2050.

## Main Sources

- **Transportation**: Cars, planes, and ships are major emitters
- **Home Energy**: Heating, cooling, and electricity use
- **Food**: Agriculture, especially livestock, contributes significantly
- **Consumer Goods**: Manufacturing and shipping of products

## Taking Action

Small individual actions—when multiplied across millions of people—can have a profound impact. Start with understanding your own footprint using tools like our Carbon Calculator.`,
      category: ArticleCategory.CARBON_FOOTPRINT,
      tags: ['basics', 'co2', 'climate', 'sustainability'],
      author: 'Dr. Emma Green',
      readTime: 5,
      published: true,
      publishedAt: new Date('2024-01-15'),
    },
    {
      title: 'The Science Behind Climate Change',
      slug: 'science-behind-climate-change',
      excerpt: 'A clear, science-based explanation of how human activities are warming our planet.',
      content: `## The Greenhouse Effect

The greenhouse effect is a natural process that warms Earth's surface. When the Sun's energy reaches Earth, some is reflected back to space and some is absorbed. Greenhouse gases (CO₂, CH₄, N₂O) trap heat in the atmosphere.

## Human Impact

Since the Industrial Revolution, human activities have increased atmospheric CO₂ from 280 ppm to over 420 ppm—the highest in 3 million years. This enhanced greenhouse effect is raising global temperatures.

## Consequences

- Rising sea levels (threatens coastal cities)
- More frequent extreme weather events
- Ecosystem disruption and biodiversity loss
- Food and water insecurity

## The Path Forward

The IPCC's Sixth Assessment Report states we must cut emissions by 45% by 2030 to limit warming to 1.5°C. Every fraction of a degree matters.`,
      category: ArticleCategory.CLIMATE_CHANGE,
      tags: ['climate', 'science', 'greenhouse', 'ipcc'],
      author: 'Prof. James Carter',
      readTime: 7,
      published: true,
      publishedAt: new Date('2024-01-20'),
    },
    {
      title: '10 Easy Ways to Reduce Your Carbon Footprint Today',
      slug: '10-ways-reduce-carbon-footprint',
      excerpt: 'Practical, actionable steps you can take right now to start living more sustainably.',
      content: `## Start Small, Think Big

You don't need to overhaul your entire life to make a difference. Here are 10 science-backed ways to reduce your impact:

1. **Switch to plant-based meals** (2-3 times/week can save ~300kg CO₂/year)
2. **Drive less** (use public transport, cycle, or carpool)
3. **Fly less** (one long-haul flight can equal months of other emissions)
4. **Improve home insulation**
5. **Switch to a green energy tariff**
6. **Eat seasonal and local produce**
7. **Reduce single-use plastics**
8. **Shop secondhand**
9. **Install a smart thermostat**
10. **Offset remaining emissions through verified projects**

## Track Your Progress

Use our Carbon Calculator to set a baseline and measure your improvements over time.`,
      category: ArticleCategory.SUSTAINABLE_LIVING,
      tags: ['tips', 'lifestyle', 'reduce', 'practical'],
      author: 'Sarah Chen',
      readTime: 4,
      published: true,
      publishedAt: new Date('2024-02-01'),
    },
    {
      title: 'Solar Energy: A Complete Beginner\'s Guide',
      slug: 'solar-energy-beginners-guide',
      excerpt: 'Everything you need to know about switching to solar power for your home.',
      content: `## How Solar Panels Work

Solar panels (photovoltaic cells) convert sunlight directly into electricity. When photons hit the silicon cells, they knock electrons loose, creating an electric current.

## Types of Solar Systems

- **Grid-tied**: Connected to the utility grid; can sell excess power back
- **Off-grid**: Completely independent with battery storage
- **Hybrid**: Combination of both

## Costs and Savings

The average home solar system costs £5,000–£10,000 in the UK. With government incentives and energy savings, the payback period is typically 7–12 years.

## Is Solar Right for You?

Consider: roof orientation (south-facing is ideal), local sunlight hours, energy consumption, and available incentives in your area.`,
      category: ArticleCategory.RENEWABLE_ENERGY,
      tags: ['solar', 'renewable', 'energy', 'home'],
      author: 'Dr. Raj Patel',
      readTime: 8,
      published: true,
      publishedAt: new Date('2024-02-10'),
    },
    {
      title: 'The Environmental Impact of Your Diet',
      slug: 'environmental-impact-of-diet',
      excerpt: 'How food choices are one of the most powerful ways individuals can fight climate change.',
      content: `## Food and Climate

The global food system accounts for approximately 26% of global greenhouse gas emissions. What we eat matters enormously.

## Emission Comparison by Diet

| Diet Type | kg CO₂e/year |
|-----------|-------------|
| High meat | ~2,500 |
| Average | ~1,700 |
| Vegetarian | ~1,000 |
| Vegan | ~600 |

## Why Meat Has Such a High Impact

- Land use change (deforestation for grazing/crops)
- Methane from livestock digestion
- Nitrous oxide from manure and fertilizers
- Water use and pollution

## Practical Steps

You don't need to go fully vegan. Research shows that:
- Eliminating beef alone has more impact than going vegan in other ways
- One "Meat-Free Monday" per week saves ~340kg CO₂/year
- Choosing local, seasonal produce reduces food miles`,
      category: ArticleCategory.FOOD_AND_DIET,
      tags: ['food', 'diet', 'vegan', 'meat', 'agriculture'],
      author: 'Lisa Thornton',
      readTime: 6,
      published: true,
      publishedAt: new Date('2024-02-15'),
    },
    {
      title: 'Electric Vehicles vs. Traditional Cars: The Full Picture',
      slug: 'electric-vehicles-vs-traditional-cars',
      excerpt: 'A balanced, data-driven analysis of EVs and their true environmental impact.',
      content: `## The Lifecycle Assessment

Comparing EVs and ICE vehicles requires looking at the full lifecycle: manufacturing, driving, and end-of-life.

## Manufacturing Phase

EV manufacturing currently produces more CO₂ than ICE vehicles, primarily due to battery production. A typical EV has ~80% higher manufacturing emissions.

## Driving Phase

This is where EVs win significantly. With the UK's current electricity grid mix, an EV emits ~70% less CO₂ per km than a petrol car.

## Breakeven Point

Most EVs break even with their ICE equivalent in 1–3 years of driving, depending on the grid's carbon intensity.

## Conclusion

EVs are significantly better for the climate, especially as grids get greener. Battery recycling technology is also improving rapidly, addressing end-of-life concerns.`,
      category: ArticleCategory.TRANSPORTATION,
      tags: ['ev', 'electric', 'cars', 'transport', 'lifecycle'],
      author: 'Marcus Williams',
      readTime: 9,
      published: true,
      publishedAt: new Date('2024-02-20'),
    },
  ];

  for (const article of articlesData) {
    await prisma.article.upsert({
      where: { slug: article.slug },
      update: {},
      create: article,
    });
  }
  console.log(`✅ ${articlesData.length} articles seeded`);

  // Add sample carbon entry for demo user
  await prisma.carbonEntry.create({
    data: {
      userId: demo.id,
      carKm: 80,
      bikeKm: 10,
      publicTransportKm: 30,
      flightKmPerYear: 3000,
      electricityKwh: 350,
      naturalGasM3: 50,
      lpgKg: 0,
      dietType: 'MIXED',
      recyclingPercent: 40,
      plasticKg: 3,
      generalWasteKg: 20,
      transportEmissions: 235.5,
      energyEmissions: 183.7,
      foodEmissions: 150,
      wasteEmissions: 29.9,
      totalMonthly: 599.1,
      totalYearly: 7189.2,
      sustainabilityScore: 45,
    },
  });
  console.log('✅ Sample carbon entry created for demo user');

  console.log('\n🌱 Seed completed successfully!');
  console.log('\n📋 Test Credentials:');
  console.log('  Admin: admin@carbontrack.io / Admin@123456');
  console.log('  Demo:  demo@carbontrack.io / Demo@123456');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(() => void prisma.$disconnect());
